# Generated by Django 5.0.6 on 2025-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_organized_by_alter_photo_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
