# Generated by Django 5.0.6 on 2025-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
