export {default as Upcoming } from './Upcoming'
export {default as HomeLayout} from './HomeLayout'
export {default as Register} from './Register'
export {default as PrevioucEvent } from './PreviousEvent'
export {default as Login} from './Login'
export {default as Error} from './Error'
export {default as Home} from './Home'
export {default as Profile} from './Profile'
export {default as CreatEvent} from './CreatEvent'
export {default as ManageEventReg} from './MangeEventReg'
export {default as EventRegister} from './EventRegister'
export {default as PhotoApproval} from './PhotoApproval'
export {default as Photopage} from './Photopage'